//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InviteApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string PairingName { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public Nullable<bool> RSVPStatus { get; set; }
        public Nullable<int> PlusOnes { get; set; }
        public Nullable<int> TotalRSVPCount { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string Hotel { get; set; }
        public Nullable<int> DinnerRSVPCount { get; set; }
        public string FoodRestrictions { get; set; }
    }
}
